[build]
  command = "npm run build"  # TypeScript dosyalarını derlemek için build scripti
  functions = "dist/routers/auth.routers.js"  # Derlenmiş fonksiyon dosyalarının bulunduğu dizin

[[redirects]]
  from = "/api/*"  # API isteklerini yönlendirmek istediğiniz yolu belirtin
  to = "/.netlify/functions/:splat"  # Fonksiyonların bulunduğu dizin
  status = 200
  force = true